/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jif_runtime_FileSystem */

#ifndef _Included_jif_runtime_FileSystem
#define _Included_jif_runtime_FileSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jif_runtime_FileSystem
 * Method:    setPolicy
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jif_runtime_FileSystem_setPolicy
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

/*
 * Class:     jif_runtime_FileSystem
 * Method:    readers
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jif_runtime_FileSystem_readers
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jif_runtime_FileSystem
 * Method:    owner
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jif_runtime_FileSystem_owner
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
