/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jif_runtime_Runtime */

#ifndef _Included_jif_runtime_Runtime
#define _Included_jif_runtime_Runtime
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: out */
/* Inaccessible static: in */
/* Inaccessible static: err */
/* Inaccessible static: pm */
/*
 * Class:     jif_runtime_Runtime
 * Method:    currentUser
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jif_runtime_Runtime_currentUser
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
